---
title: "STM_Model US k-value analysis"
author: "Charlie J. Gomez, Harshvardhan Singh"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('stm')
library(dplyr)
library(stringr)
library(wordcloud)
#Read csv file
data = read.csv("preprocessed_data_Jul14.csv")


##Topic generation for US (in collaboration) publications

data_collab <- data[data[["US"]] != 0,]

# Save the original title data for future use
data_collab$original_concatenated_title_abstract <- data_collab$concatenated_title_abstract

#pre-processing the titles using textProcessor from the stm package
processed_text <- textProcessor(data_collab$concatenated_title_abstract, metadata = data_collab) 

# Further prepare the data by removing low-frequency terms
out_text <- prepDocuments(processed_text$documents, processed_text$vocab, processed_text$meta)
docs_text <- out_text$documents
vocab_text <- out_text$vocab
meta_text <- out_text$meta


#Prepare data
plotRemoved(processed_text$documents, lower.thresh = seq(1, 200, by = 100))
out_text <- prepDocuments(processed_text$documents, processed_text$vocab, processed_text$meta, lower.thresh = 8)

str(out_text$meta)

# Initialize an empty formula string
prevalence_formula_str <- "~"

# Define the publication intervals
pub_intervals <- c("pub_interval_2020_2022", "pub_interval_2015_2019", "pub_interval_2010_2014", 
                   "pub_interval_2005_2009", "pub_interval_2000_2004", "pub_interval_1995_1999",
                   "pub_interval_1985_1994", "pub_interval_1975_1984", "pub_interval_1965_1974",
                   "pub_interval_1900_1964", "pub_interval_1824_1899")

# Add each publication interval to the formula string
for (interval in pub_intervals) {
  # add an if statement to handle the first addition (without '+')
  if (prevalence_formula_str == "~") {
    prevalence_formula_str <- paste(prevalence_formula_str, interval)
  } else {
    prevalence_formula_str <- paste(prevalence_formula_str, "+", interval)
  }
}


# Convert the string to a formula
prevalence_formula <- as.formula(prevalence_formula_str)
print(prevalence_formula)

Kvals <- seq(from = 5, to = 40, by = 5)  # K values to try
search_results <- searchK(documents = out_text$documents, 
                          vocab = out_text$vocab, 
                          K = Kvals, 
                          prevalence = prevalence_formula, 
                          data = out_text$meta, 
                          init.type = "Spectral", 
                          verbose = FALSE)

# Plot the results
plot(search_results)

```