---
title: "Research Title Analysis (KeyATM)"
author: "Charles J. Gomez, Harshvardhan Singh"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading data for quanteda

```{r}
# Load the library
library(keyATM)
library(quanteda)
library(readtext)


# Read the CSV file
data <- read.csv("INPUT_SQL_Text_Data_Astronomy_and_Astrophysics.csv")
text_data <- data$title

# Preprocessing
key_corpus <- corpus(text_data)

# Covariate data
covariate_data <- data[, c("publication_year", "country")]
key_corpus <- corpus(text_data, docvars = covariate_data)
#docvars(key_corpus, c("publication_year", "country")) <- covariate_data

#Creating token object
key_token <- tokens(key_corpus)

# Createing a document-feature matrix (dfm object) from the token object
key_dfm <- dfm(key_token)

```

## Preprocessing data

```{r}

library(keyATM)
library(quanteda)
library(magrittr)

#remove punctuations and unnecessary characters
data_tokens <- tokens(
    data$title,
    remove_numbers = FALSE,
    remove_punct = TRUE,
    remove_symbols = TRUE,
    remove_separators = TRUE,
    remove_url = TRUE
  ) %>%
  tokens_tolower() %>%    #converts all characters into lower cases
  tokens_remove(
    c(stopwords("english"),
      "may", "shall", "can",
      "must", "upon", "with", "without"
    )
  ) %>%
  tokens_select(min_nchar = 3)

#Before loading data into the keyATM, construct a document-feature matrix (dfm object)
data_dfm <- dfm(data_tokens) %>%
              dfm_trim(min_termfreq = 5, min_docfreq = 2)
ncol(data_dfm)  # the number of unique words


# Filter out documents with length 0
#data_dfm <- data_dfm[ndoc(data_dfm) > 0, ]
data_dfm <- dfm_subset(data_dfm, ntoken(data_dfm) > 0)

# Read the document-feature matrix using keyATM_read()
keyATM_docs <- keyATM_read(texts = data_dfm)

# Summary of keyATM_docs
summary(keyATM_docs)

```
Preparing keywords

```{r}
keywords <- list(
 Topic1 = c("burst", "gamma-ray", "quasar", "line", "discoveri"), 
 Topic2 = c("variabl", "studi", "ngc", "galaxi", "ultraviolet"), 
 Topic3 = c("solar", "use", "measur", "infrar", "variat"), 
 Topic4 = c("binari", "hole", "black", "accret", "system"), 
 Topic5 = c("dwarf", "planet", "star", "disk", "around"), 
 Topic6 = c("star", "cluster", "format", "massiv", "globular"), 
 Topic7 = c("supernova", "type", "remnant", "spectra", "light"), 
 Topic8 = c("nebula", "planetari", "wind", "young", "outflow"), 
 Topic9 = c("galaxi", "redshift", "survey", "sky", "high"), 
 Topic10 = c("galaxi", "structur", "gas", "spiral", "local"), 
 Topic11 = c("model", "distribut", "univers", "energi", "cosmic"), 
 Topic12 = c("dust", "abund", "interstellar", "comet", "chemic"), 
 Topic13 = c("magnet", "field", "solar", "coron", "shock"), 
 Topic14 = c("gravit", "effect", "lens", "background", "cosmic"), 
 Topic15 = c("x-ray", "radio", "emiss", "pulsar", "sourc"), 
 Topic16 = c("galact", "activ", "stellar", "region", "luminos"), 
 Topic17 = c("observ", "cloud", "chandra", "magellan", "molecular"), 
 Topic18 = c("survey", "telescop", "imag", "space", "hubbl"), 
 Topic19 = c("dark", "halo", "matter", "galaxi", "mass"), 
 Topic20 = c("new", "evid", "origin", "rotat", "dynam")
)

```
Checking Keywords
```{r}
key_viz <- visualize_keywords(docs = keyATM_docs, keywords = keywords)
key_viz

#save figure
key_viz <- visualize_keywords(docs = keyATM_docs, keywords = keywords)
save_fig(key_viz, "/Users/harshvardhansingh/Documents/keyword.pdf", width = 6.5, height = 4)

#get the actual values
values_fig(key_viz)
```
Preparing Covariates
```{r}
vars <- docvars(key_dfm)
head(vars)
```