---
title: "STM Model"
author: "Charlie J. Gomez, Harshvardhan Singh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
#Read csv file
data = read.csv("INPUT_SQL_Text_Data_Astronomy_and_Astrophysics.csv")
data_CountryColumn <- data$country

#We removed all instances of middle authors' country codes. This step involved replacing the pattern "\w+\+middle" with an empty string, effectively eliminating all middle author affiliations. The resulting country codes were then trimmed to remove any leading or trailing spaces

data$country <- gsub("\\w+\\+middle", "", data$country)
data$country <- trimws(data$country)
print(head(data$country, 50))

#We removed the "+first" and "+last" strings from the remaining country codes using another regular expression substitution. The pattern "\+last|\+first" was replaced with an empty string, ensuring that only the country codes remained

data$country <- gsub("\\+last|\\+first", "", data$country)
# Remove any extra spaces resulting from the removal
data$country <- sapply(strsplit(data$country, "\\s+"), function(x) paste(x[x != ""], collapse = " "))

print(head(data$country, 50))


str(data)


start_column <- which(names(data) == "publication_year")
end_column <- which(names(data) == "country")

data_forSampling <- data[, start_column:end_column]


set.seed(123)  
#sample_size <- 21000  
sample_size <- 8000
sample_rows <- sample(nrow(data_forSampling), sample_size)
data <- data_forSampling[sample_rows, ]
#data = read.csv("INPUT_SQL_Text_Data_Astronomy_and_Astrophysics.csv")

library('stm')

#pre-processing the titles
processed_titles <- textProcessor(data$title, metadata = data) 
out_titles <- prepDocuments(processed_titles$documents, processed_titles$vocab, processed_titles$meta)
docs_titles <- out_titles$documents
vocab_titles <- out_titles$vocab
meta_titles <- out_titles$meta


#Prepare data
plotRemoved(processed_titles$documents, lower.thresh = seq(1, 200, by = 100))
out_titles <- prepDocuments(processed_titles$documents, processed_titles$vocab, processed_titles$meta, lower.thresh = 15)

str(out_titles$meta)

# Create a formula that includes all country dummy variables
country_vars <- paste(names(data)[4], collapse = " + ")
prevalence_formula <- as.formula(paste("~ publication_year + ", country_vars))

poliblogPrevFit_titles <- stm(documents = out_titles$documents, 
                             vocab = out_titles$vocab, 
                              K = 20, 
                              prevalence = prevalence_formula, 
                              data = out_titles$meta, 
                              init.type = "Spectral",
                              max.em.its = 1000,
                              gamma.prior = 'L1')

#poliblogPrevFit_titles <- stm(documents = out_titles$documents, 
#                              vocab = out_titles$vocab, 
#                              K = 20, 
#                              prevalence = ~publication_year, 
#                              data = out_titles$meta, 
#                              init.type = "Spectral",
#                              max.em.its = 1000)


poliblogSelect <- selectModel(out_titles$documents, 
                              out_titles$vocab, 
                              K = 20, 
                              prevalence = ~publication_year + country, 
                              max.em.its = 1000, 
                              data = out_titles$meta, 
                              runs = 2, #try 2
                              seed = 8458159,
                              gamma.prior = 'L1')



plotModels(poliblogSelect, pch = c(1, 2, 3, 4), legend.position = "bottomright")

selectedmodel <- poliblogSelect$runout[[1]]

options(stm.em_max_iter = 2000, stm.expect_max_iter = 2000)
storage <- stm(
  documents = out_titles$documents,
  vocab = out_titles$vocab,
  K = 20,
  prevalence = ~publication_year + country,
  data = out_titles$meta,
  gamma.prior = 0.5
)

```

