---
title: "STM Model"
author: "Charlie J. Gomez, Harshvardhan Singh"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Titles Analysis

```{r cache=TRUE}

library(stringr)
#Read csv file
data = read.csv("INPUT_SQL_Text_Data_Astronomy_and_Astrophysics.csv")
data_CountryColumn <- data$country

#We removed all instances of middle authors' country codes. This step involved replacing the pattern "\w+\+middle" with an empty string, effectively eliminating all middle author affiliations. The resulting country codes were then trimmed to remove any leading or trailing spaces

data$country <- gsub("\\w+\\+middle", "", data$country)
data$country <- trimws(data$country)
print(head(data$country, 50))

#We removed the "+first" and "+last" strings from the remaining country codes using another regular expression substitution. The pattern "\+last|\+first" was replaced with an empty string, ensuring that only the country codes remained

data$country <- gsub("\\+last|\\+first", "", data$country)
# Remove any extra spaces resulting from the removal
data$country <- sapply(strsplit(data$country, "\\s+"), function(x) paste(x[x != ""], collapse = " "))

print(head(data$country, 50))



# calculate the percentage count of each country code in a vector
#calculate_percentage <- function(vec) {
#  counts <- table(vec)
#  percentages <- prop.table(counts) * 100
#  formatted <- paste0(round(percentages, 1), "%", names(percentages))
#  paste(formatted, collapse = " ")
#}

# Apply the calculate_percentage function to each row in the 'country' column
#data$country <- sapply(strsplit(data$country, "\\s+"), calculate_percentage)

# Print the modified 'country' column (first 20)
#print(head(data$country, 50))




# Calculate percentage count of each country code in a vector
calculate_percentage <- function(vec) {
  counts <- table(vec)
  percentages <- prop.table(counts) * 100
  return(percentages)
}

# Apply the calculate_percentage function to each row in the 'country' column
percentage_counts <- lapply(strsplit(data$country, "\\s+"), calculate_percentage)

# Get all unique countries
all_countries <- unique(unlist(lapply(percentage_counts, names)))

# Initialize a new data frame to hold the percentages
percentage_df <- data.frame(matrix(ncol = length(all_countries), nrow = length(percentage_counts)))
names(percentage_df) <- all_countries

# Fill the data frame with percentages
for (i in seq_along(percentage_counts)) {
  country_names <- names(percentage_counts[[i]])
  country_percentages <- percentage_counts[[i]]
  percentage_df[i, country_names] <- country_percentages
}

# Replace NA values with 0
percentage_df[is.na(percentage_df)] <- 0

# Combine the original data with the new percentage-encoded country columns
data <- cbind(data, percentage_df)

str(data)


#start_column <- which(names(data) == "publication_year")
#end_column <- which(names(data) == "country")

#data_forSampling <- data[, start_column:end_column]


set.seed(123)  
#sample_size <- 21000  
sample_size <- 8000
sample_rows <- sample(nrow(data), sample_size)
data <- data[sample_rows, ]
#data = read.csv("INPUT_SQL_Text_Data_Astronomy_and_Astrophysics.csv")

library('stm')

#pre-processing the titles
processed_titles <- textProcessor(data$title, metadata = data) 
out_titles <- prepDocuments(processed_titles$documents, processed_titles$vocab, processed_titles$meta)
docs_titles <- out_titles$documents
vocab_titles <- out_titles$vocab
meta_titles <- out_titles$meta


#Prepare data
plotRemoved(processed_titles$documents, lower.thresh = seq(1, 200, by = 100))
out_titles <- prepDocuments(processed_titles$documents, processed_titles$vocab, processed_titles$meta, lower.thresh = 15)

str(out_titles$meta)

# Create the base formula
prevalence_formula_str <- "~publication_year"

# Add each country variable to the formula string
for (i in 8:106) {
  prevalence_formula_str <- paste(prevalence_formula_str, "+", names(data)[i])
}

# Convert the string to a formula
prevalence_formula <- as.formula(prevalence_formula_str)
print(prevalence_formula)

# Run STM model
poliblogPrevFit_titles <- stm(documents = out_titles$documents, 
                             vocab = out_titles$vocab, 
                             K = 20, 
                             prevalence = prevalence_formula, 
                             data = out_titles$meta, 
                             init.type = "Spectral",
                             max.em.its = 1000,
                             gamma.prior = 'L1')


#poliblogPrevFit_titles <- stm(documents = out_titles$documents, 
#                              vocab = out_titles$vocab, 
#                              K = 20, 
#                              prevalence = ~publication_year, 
#                              data = out_titles$meta, 
#                              init.type = "Spectral",
#                              max.em.its = 1000)


poliblogSelect <- selectModel(out_titles$documents, 
                              out_titles$vocab, 
                              K = 20, 
                              prevalence = ~publication_year + country, 
                              max.em.its = 1000, 
                              data = out_titles$meta, 
                              runs = 2, #try 2
                              seed = 8458159,
                              gamma.prior = 'L1')



plotModels(poliblogSelect, pch = c(1, 2, 3, 4), legend.position = "bottomright")

selectedmodel <- poliblogSelect$runout[[1]]

options(stm.em_max_iter = 2000, stm.expect_max_iter = 2000)
storage <- stm(
  documents = out_titles$documents,
  vocab = out_titles$vocab,
  K = 20,
  prevalence = ~publication_year + country,
  data = out_titles$meta,
  gamma.prior = 0.5
)



```

