---
title: "Topic Defined and Datasets Combined"
author: "Harshvardhan Singh, Charles J. Gomez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cache=TRUE}
library(stringr)
library(dplyr)
library(tibble)

data = read.csv("topics_1990_1994.csv")
data <- data %>%
  add_column(time_period = "1990-1994", .after = "year")

data <- data %>%
  mutate(Topic_Name = case_when(
    topic == 'V1' ~ "Primary Processes and Chemical Reactions",
    topic == 'V2' ~ "Spatial Analysis and Frequency Parameters",
    topic == 'V3' ~ "Flow Dynamics and Doppler Measurement Techniques",
    topic == 'V4' ~ "Spectral Data Analysis and Light Properties",
    topic == 'V5' ~ "Galactic Structure and Interstellar Phenomena",
    topic == 'V6' ~ "Temperature Variations and Biological Rhythms",
    topic == 'V7' ~ "Advancements in Astronomical Exploration",
    topic == 'V8' ~ "Quantum Effects in Material Sciences",
    topic == 'V9' ~ "Astrophysical Phenomena in High-Energy Bands",
    topic == 'V10' ~ "Robotic Systems and Control Mechanisms",
    topic == 'V11' ~ "Magnetic Properties and Phase Transitions",
    topic == 'V12' ~ "Molecular Dynamics and Crystal Structures",
    topic == 'V13' ~ "Computational Techniques in Physics",
    topic == 'V14' ~ "Stellar Formation and Interstellar Clouds",
    topic == 'V15' ~ "Thermal Effects and Electrical Properties",
    topic == 'V16' ~ "Cosmic Particles and Radiation Dynamics",
    topic == 'V17' ~ "Exploring Galactic Centers and Black Holes",
    topic == 'V18' ~ "Stellar Behavior and Binary Star Systems",
    topic == 'V19' ~ "Remote Sensing and Satellite Technology",
    topic == 'V20' ~ "Genetic Features and Cellular Dynamics in Humans",
    topic == 'V21' ~ "Laser Diagnostics and Plasma Spectroscopy",
    topic == 'V22' ~ "Innovations in Telescope and Space Optics",
    topic == 'V23' ~ "Accretion Disks and Models of Stellar Evolution",
    topic == 'V24' ~ "Atmospheric Monitoring Using Infrared Technologies",
    topic == 'V25' ~ "Spacecraft Trajectory and Operational Strategy",
    topic == 'V26' ~ "Biological Sampling with Ultrasound Techniques",
    topic == 'V27' ~ "Earthquake Research and New Methodologies",
    topic == 'V28' ~ "Gravitational Interactions and Theoretical Physics",
    topic == 'V29' ~ "Space Debris and Low Earth Orbit Dynamics",
    topic == 'V30' ~ "Electron Dynamics and Structural Spectra",
    topic == 'V31' ~ "Fluid Dynamics in Spherical Systems",
    topic == 'V32' ~ "Advances in NMR Spectroscopy and Compound Synthesis",
    topic == 'V33' ~ "Stellar Winds and Their Cosmological Implications",
    topic == 'V34' ~ "High-Resolution Imaging Technologies",
    topic == 'V35' ~ "Sensitivity and Precision in Detection Applications",
    is.na(topic) ~ NA_character_, # Handle NA values explicitly if needed
    TRUE ~ NA_character_ # For any other case, return NA_character_
  ))


```

```{r cache=TRUE}
data1 = read.csv("topics_1995_1999.csv")
data1 <- data1 %>%
  add_column(time_period = "1995-1999", .after = "year")

data1 <- data1 %>%
  mutate(Topic_Name = case_when(
    topic == 'V1' ~ "Astronomy and Historical Perspectives",
    topic == 'V2' ~ "Spectroscopy and Environmental Shifts",
    topic == 'V3' ~ "Active Galactic Nuclei and Solar Research",
    topic == 'V4' ~ "Variability and Rate Changes in Astronomy",
    topic == 'V5' ~ "Cosmology, Dark Matter, and Neutrinos",
    topic == 'V6' ~ "Structural Crystallography and Molecular Vibrations",
    topic == 'V7' ~ "Stellar Evolution and Galactic Structures",
    topic == 'V8' ~ "Primary Conditions and Material Sciences",
    topic == 'V9' ~ "Geophysical Fluid Dynamics and Motion",
    topic == 'V10' ~ "Gravitational Radiation and Lensing",
    topic == 'V11' ~ "Galactic Dynamics and Black Hole Accretion",
    topic == 'V12' ~ "Cosmic Microwave Background and Ray Analysis",
    topic == 'V13' ~ "Cellular Interactions and Genetic Regulation",
    topic == 'V14' ~ "Space Telescopes and Spectrometry",
    topic == 'V15' ~ "Spectral Analysis and Simulation Techniques",
    topic == 'V16' ~ "Atmospheric Detection and Planetary Orbits",
    topic == 'V17' ~ "Theoretical Physics and Particle Analysis",
    topic == 'V18' ~ "Academic Publications and Cultural Studies",
    topic == 'V19' ~ "Optical Properties and Thin Film Physics",
    topic == 'V20' ~ "Gamma-ray Observations and Variable Stars",
    topic == 'V21' ~ "Polar Effects and Seismic Activities",
    topic == 'V22' ~ "Doppler Techniques and Blood Flow Analysis",
    topic == 'V23' ~ "High-Resolution Spectroscopy and Molecular Studies",
    topic == 'V24' ~ "Temperature Measurement and Surface Analysis",
    topic == 'V25' ~ "Galaxy Evolution and Redshift Surveys",
    topic == 'V26' ~ "Solar Magnetism and Coronal Studies",
    topic == 'V27' ~ "Natural Phenomena and Evidential Probes",
    topic == 'V28' ~ "Spectra and Diagnostic Techniques",
    topic == 'V29' ~ "Organic Synthesis and Molecular Chains",
    topic == 'V30' ~ "X-ray Astronomy and Supernova Remnants",
    topic == 'V31' ~ "Interstellar Medium and Cosmic Dust",
    topic == 'V32' ~ "Plasma Physics and Atomic Reactions",
    topic == 'V33' ~ "Satellite Systems and Trajectory Optimization",
    topic == 'V34' ~ "Spatial Distribution and Particle Dynamics",
    topic == 'V35' ~ "Dynamics of Localized Processes and Chemical Enhancements",
    TRUE ~ NA_character_ # Default case for handling unexpected values
  ))


```

```{r cache=TRUE}
data2 = read.csv("topics_2000_2004.csv")
data2 <- data2 %>%
  add_column(time_period = "2000-2004", .after = "year")

data2 <- data2 %>%
  mutate(Topic_Name = case_when(
    topic == 'V1' ~ "Primary Variations and Cellular Behavior",
    topic == 'V2' ~ "Computational Trends and Environmental Challenges",
    topic == 'V3' ~ "Astrophysics and Nuclear Growth",
    topic == 'V4' ~ "Stellar Objects and Extreme Astrophysical Phenomena",
    topic == 'V5' ~ "Advanced Text Encoding and Publication Standards in Astronomy",
    topic == 'V6' ~ "Exoplanetary Searches and Galactic Surveys",
    topic == 'V7' ~ "Laser Technology and Plasma Studies",
    topic == 'V8' ~ "Galactic Evolution and Cosmic Structures",
    topic == 'V9' ~ "Gravitational Wave Detection and Astrophysical Experiments",
    topic == 'V10' ~ "Methodological Advances in Parameter Estimation",
    topic == 'V11' ~ "Dynamics and Simulations of Astrophysical Systems",
    topic == 'V12' ~ "Astronomical Instrumentation and Calibration Techniques",
    topic == 'V13' ~ "Historical and Conceptual Foundations of Cosmology",
    topic == 'V14' ~ "Spectroscopy and Molecular Vibrational Studies",
    topic == 'V15' ~ "Stellar Formation and Evolution",
    topic == 'V16' ~ "High-Energy Astrophysical Phenomena",
    topic == 'V17' ~ "Supernovae, Neutrinos, and Cosmic Particles",
    topic == 'V18' ~ "Flow Measurement Techniques in Astrophysics",
    topic == 'V19' ~ "Crystallography and Quantum Studies",
    topic == 'V20' ~ "Statistical Analyses in Sports and Economics",
    topic == 'V21' ~ "Telescopic Innovations and Observational Technologies",
    topic == 'V22' ~ "Accretion Processes and Black Hole Physics",
    topic == 'V23' ~ "Atomic and Molecular Structure in Astrophysics",
    topic == 'V24' ~ "Neutron Stars and Oscillation Phenomena",
    topic == 'V25' ~ "Interstellar Medium and Cosmic Dust",
    topic == 'V26' ~ "Model Testing and Theoretical Predictions",
    topic == 'V27' ~ "Space Exploration and Hubble Telescope Innovations",
    topic == 'V28' ~ "Molecular Clouds and Ultraviolet Astronomy",
    topic == 'V29' ~ "Theoretical Physics and Cosmological Models",
    topic == 'V30' ~ "Surface Physics and Thin Film Technologies",
    topic == 'V31' ~ "Cosmic Microwave Background and Cosmology",
    topic == 'V32' ~ "Dark Matter and Galactic Structures",
    topic == 'V33' ~ "Radio Astronomy and Pulsar Studies",
    topic == 'V34' ~ "Solar Physics and Magnetohydrodynamics",
    topic == 'V35' ~ "Spectral Analysis and Thermal Processes",
    is.na(topic) ~ NA_character_,
    TRUE ~ NA_character_
  ))


```

```{r cache=TRUE}
data3 = read.csv("topics_2005_2009.csv")
data3 <- data3 %>%
  add_column(time_period = "2005-2009", .after = "year")

data3 <- data3 %>%
  mutate(Topic_Name = case_when(
    topic == 'V1' ~ "Chemical Processes in Astrophysics",
    topic == 'V2' ~ "Advances in Telescope and Instrumentation Technology",
    topic == 'V3' ~ "Galaxy Surveys and Cosmic Structures",
    topic == 'V4' ~ "Spacecraft Trajectory and Control Systems",
    topic == 'V5' ~ "Astrophysical Data Analysis Techniques",
    topic == 'V6' ~ "Quantitative Methods in Spectral Analysis",
    topic == 'V7' ~ "Exoplanet Detection and Characterization",
    topic == 'V8' ~ "Development and Status of Observatories",
    topic == 'V9' ~ "Galactic Clusters and Stellar Evolution",
    topic == 'V10' ~ "Stellar Composition and Isotope Analysis",
    topic == 'V11' ~ "Cosmology and Fundamental Physics",
    topic == 'V12' ~ "Thermal Processes and Dynamical Properties in Astrophysics",
    topic == 'V13' ~ "Solar Activity and Heliospheric Physics",
    topic == 'V14' ~ "Supernova Mechanics and Simulation",
    topic == 'V15' ~ "Spectroscopy and Molecular Emissions",
    topic == 'V16' ~ "Magnetic Fields in Astrophysical Bodies",
    topic == 'V17' ~ "Spectroscopic Studies of Quantum Structures",
    topic == 'V18' ~ "Temporal Variations in Astrophysical Observations",
    topic == 'V19' ~ "History and Evolution of the Universe",
    topic == 'V20' ~ "Advances in Doppler Imaging and Spectroscopy",
    topic == 'V21' ~ "Black Hole Physics and Accretion Processes",
    topic == 'V22' ~ "Observational X-ray and Gamma-ray Astronomy",
    topic == 'V23' ~ "Analytical Techniques in Astrophysics",
    topic == 'V24' ~ "Dark Matter and Energy in Cosmology",
    topic == 'V25' ~ "Interstellar Medium and Dust Analysis",
    topic == 'V26' ~ "Adaptive Optics and Ultraviolet Astronomy",
    topic == 'V27' ~ "Cellular and Molecular Astrophysics",
    topic == 'V28' ~ "Stellar Oscillations and Neutron Stars",
    topic == 'V29' ~ "Cosmic Rays and High Energy Astrophysics",
    topic == 'V30' ~ "Cosmic Microwave Background and Large Scale Structure",
    topic == 'V31' ~ "Plasma Physics in Space Environments",
    topic == 'V32' ~ "Space Missions and Satellite Calibration",
    topic == 'V33' ~ "Variability in Binary and X-ray Stars",
    topic == 'V34' ~ "Star Formation and Evolution of Compact Objects",
    topic == 'V35' ~ "Modeling and Simulation in Astrophysical Systems",
    is.na(topic) ~ NA_character_, # Handle NA values explicitly if needed
    TRUE ~ NA_character_ # For any other case, return NA_character_
  ))


```

```{r cache=TRUE}
data4 = read.csv("topics_2010_2015.csv")
data4 <- data4 %>%
  add_column(time_period = "2010-2015", .after = "year")

data4 <- data4 %>%
  mutate(Topic_Name = case_when(
    topic == 'V1' ~ "Galactic Regions and Stellar Kinematics",
    topic == 'V2' ~ "Astrophysical Data Analysis and Surveys",
    topic == 'V3' ~ "Relativistic Jets and Gamma-ray Bursts",
    topic == 'V4' ~ "Educational Programs in Astrophysics",
    topic == 'V5' ~ "Innovations in Physics and Global Research",
    topic == 'V6' ~ "Dark Matter Detection and Planetary Disk Studies",
    topic == 'V7' ~ "White Dwarf Binaries and Supernovae",
    topic == 'V8' ~ "Material Sciences in Astrophysics",
    topic == 'V9' ~ "Cosmological Models and Universal Parameters",
    topic == 'V10' ~ "Spectroscopy in Astrophysics",
    topic == 'V11' ~ "Galactic Evolution and Black Hole Dynamics",
    topic == 'V12' ~ "Laser-Induced Plasma Applications",
    topic == 'V13' ~ "Sociology of Sports in International Contexts",
    topic == 'V14' ~ "Doppler Techniques and Flow Measurement in Astrophysics",
    topic == 'V15' ~ "Computational Methods for Astrophysical Analysis",
    topic == 'V16' ~ "Advances in Spectroscopy and Imaging Techniques",
    topic == 'V17' ~ "Cluster Formation and Dynamics in the Cosmos",
    topic == 'V18' ~ "Variability and Adaptation in Cosmic Phenomena",
    topic == 'V19' ~ "Time-Series Analysis in Astronomical Studies",
    topic == 'V20' ~ "Solar Physics and Instrumentation Calibration",
    topic == 'V21' ~ "Stellar Evolution and Chemical Abundances",
    topic == 'V22' ~ "Interstellar Medium and Cosmic Dust Analysis",
    topic == 'V23' ~ "Trajectory Control and Robotics in Space Missions",
    topic == 'V24' ~ "Chemical Synthesis and Reaction Dynamics in Space",
    topic == 'V25' ~ "Observational Techniques in X-ray Astronomy",
    topic == 'V26' ~ "Medical Studies and Treatment Reviews in Space Science",
    topic == 'V27' ~ "Cosmic Rays and Gamma-ray Astronomy",
    topic == 'V28' ~ "Magnetic and Structural Properties of Cosmic Objects",
    topic == 'V29' ~ "Exoplanet Discovery and Atmospheric Characterization",
    topic == 'V30' ~ "Simulation of Molecular Clouds and Star Formation",
    topic == 'V31' ~ "Variability and Modulation in Stellar Activity",
    topic == 'V32' ~ "Satellite Missions and Earth Observation Techniques",
    topic == 'V33' ~ "Telescope Design and Space Observatories",
    topic == 'V34' ~ "Dynamics and Mechanisms in Astrophysical Processes",
    topic == 'V35' ~ "Effects and Correlations in Astrophysical Phenomena",
    is.na(topic) ~ NA_character_, # Handle NA values explicitly if needed
    TRUE ~ NA_character_ # For any other case, return NA_character_
  ))

```

```{r cache=TRUE}
combined_data <- bind_rows(data, data1, data2, data3, data4)

write.csv(combined_data, "PROJECT_Apollo_STM_Data.csv", row.names = FALSE)

```


